# Generated by Django 3.1.5 on 2021-01-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleave',
            name='confirm',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Waiting for apprave', 'Waiting for apprave'), ('Not approved', 'Not approved')], default='Waiting for apprave', max_length=60, null=True),
        ),
    ]
